make-test-squashfs: avoid writing output files as root.
If make-test-squashfs is ran through sudo, then give ownership
to the SUDO_USER.  This is necessary as some systems we build on
have remote-mounted /home.  There, you cannot create files as root.
so even a 'cp --preserve=ownership' will fail as that will first
write the file as root and then chmod it.

So the jump through 'tee' to avoid writing files as root.

diff --git a/make-test-squashfs b/make-test-squashfs
--- a/make-test-squashfs
+++ b/make-test-squashfs
@@ -39,7 +39,8 @@ mydir=$(dirname "$0") || fail
 mydir=$(cd "$mydir" && pwd) || fail
 start_d=${PWD}
 
-cd "${TEMP_D}"
+mkdir "${TEMP_D}/fsroot" || fail
+cd "${TEMP_D}/fsroot"
 
 cp "${mydir}"/README.md . || fail
 mkdir my.d || fail
@@ -100,9 +101,19 @@ if $amroot; then
     mknod dir2/overlayfs-whiteout.txt c 0 0
 fi
 
-cd "${mydir}"
-rm -f "$outfile"
-out=$(mksquashfs "${TEMP_D}/" "$outfile" -comp xz 2>&1) || {
+out=$(mksquashfs "${TEMP_D}/fsroot" "${TEMP_D}/squashfs.img" -comp xz 2>&1) || {
     fail "failed mksquashfs: $out"
 }
+
+cd "${start_d}"
+rm -f "$outfile" || fail "failed to remove $outfile"
+if [ -n "$SUDO_USER" -a "$(id -u)" = "0" ]; then
+    # some systems you can't write files as root to HOME.
+    sudo "--user=$SUDO_USER" tee "$outfile" >/dev/null < "$TEMP_D/squashfs.img" ||
+        fail "failed to write file as $SUDO_USER via tee"
+else
+    cp "${TEMP_D}/squashfs.img" "$outfile" ||
+        fail "failed cp <tmpdir>/squashfs.img $outfile"
+fi
+
 exit 0
